version: '3.3'

services:
  
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: RAMADI
      POSTGRES_PASSWORD: Sophist
      POSTGRES_DB: Dev_Env-Data
    volumes:
      - postgres_db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: RAMADI@admin.com
      PGADMIN_DEFAULT_PASSWORD: Sophist
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_db:/var/lib/pgadmin

  vscode:
    image: codercom/code-server:latest
    container_name: vscode
    environment:
      PASSWORD: Sophist
    volumes:
      - ./JavaApp/:/home/coder/project
    ports:
      - "8085:8080"

  java:
    image: openjdk:latest
    container_name: java
    depends_on:
      - postgres
    volumes:
      - ./JavaApp/:/usr/src/app
    working_dir: /usr/src/app
    command:     bash -c "
        javac TraineeApp.java &&
        java -cp '.:postgresql-42.6.0.jar' TraineeApp
      "
    tty: true

  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    volumes:
      - filebrowser_data:/srv
    ports:
      - "8081:80"
    environment:
      FB_BASEURL: /
      FB_NOAUTH: "false"
      FB_PASSWORD: Sophist

volumes:
  pgadmin_db:
          external: true
  postgres_db:
          external: true
  JavaApp:
  filebrowser_data:

